import { chromium } from "playwright";
import { createHmac } from "node:crypto";
import { requireLocalDb } from "./scripts/local-only.mjs";
requireLocalDb("probe");
const BASE="http://127.0.0.1:3000", S=process.env.AUTH_SECRET;
const tok=(u)=>{const p=Buffer.from(JSON.stringify({...u,exp:Math.floor(Date.now()/1000)+3600})).toString("base64url");
  return `${p}.${createHmac("sha256",S).update(p).digest("base64url")}`;};
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-proxy-server","--no-sandbox"]});
const ctx=await b.newContext({viewport:{width:1440,height:950}});
await ctx.addCookies([{name:"tb_session",value:tok({id:1,actorId:1,name:"권정혁",role:"lead",email:"lead@local"}),domain:"127.0.0.1",path:"/"}]);
const p=await ctx.newPage();
p.on("pageerror",e=>console.log("PAGEERROR:",e.message));
await p.goto(BASE+"/tasks?panel=task:new",{waitUntil:"networkidle"});
await p.waitForTimeout(1500);
await p.locator(".frn-skip").first().click({timeout:1500}).catch(()=>{});
await p.waitForTimeout(800);
console.log("url:", p.url());
console.log(".ntm-side (열기 전):", await p.locator(".ntm-side").count());
console.log(".ntm-adv 버튼:", await p.locator(".ntm-adv").count(), (await p.locator(".ntm-adv").innerText().catch(()=>"")).trim());
await p.locator(".ntm-adv").click().catch(e=>console.log("고급 못 누름:",e.message));
await p.waitForTimeout(500);
console.log(".ntm-side (연 뒤):", await p.locator(".ntm-side").count());
console.log("[role=dialog]:", await p.locator("[role=dialog]").count(), await p.locator("[role=dialog]").evaluateAll(e=>e.map(x=>x.getAttribute("aria-label"))));
console.log("본문 ntm-fl:", await p.locator(".ntm-main .ntm-fl").allInnerTexts().catch(()=>[]));
console.log(".pp 개수:", await p.locator(".pp").count());
console.log(".pp 안:", (await p.locator(".pp").first().innerText().catch(()=>"(없음)")).replace(/\s+/g," ").slice(0,200));
console.log(".pp-b 버튼 수:", await p.locator(".pp-b").count());
console.log(".ntm-main .pcb-v:", await p.locator(".ntm-main .pcb-v").count());
console.log(".pcb-v:", await p.locator(".ntm-side .pcb-v").count());
const row = p.locator('.ntm-side .prop-row:has(.prop-l:text-is("프로젝트")) .pcb-v');
console.log("선택자 행:", await row.count());
if (await row.count()) {
  await row.click(); await p.waitForTimeout(400);
  console.log(".pcb-q:", await p.locator(".pcb-q").count());
  await p.locator(".pcb-q").fill("존재하지않을이름ZZZ"); await p.waitForTimeout(400);
  console.log(".pcb-new:", await p.locator(".pcb-new").count());
  console.log("pop 내용:", (await p.locator(".pcb-pop").innerText().catch(()=>"(없음)")).replace(/\s+/g," ").slice(0,120));
}
await p.screenshot({path:"/tmp/probe-newtask.png", fullPage:true});
await ctx.close(); await b.close();
