import { chromium } from "playwright";
import { createHmac } from "node:crypto";
import pg from "pg";
import { requireLocalDb } from "./scripts/local-only.mjs";
requireLocalDb("probe2");
const BASE="http://127.0.0.1:3000", S=process.env.AUTH_SECRET;
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
const tok=(u)=>{const p=Buffer.from(JSON.stringify({...u,exp:Math.floor(Date.now()/1000)+3600})).toString("base64url");
  return `${p}.${createHmac("sha256",S).update(p).digest("base64url")}`;};
const rows=(await pool.query(`SELECT id, title, due_date::text d, assignee_id, area_id FROM task
  WHERE is_active AND parent_task_id IS NULL AND status <> 'done' ORDER BY id LIMIT 2`)).rows;
const before=rows.map(r=>({...r}));
await pool.query(`UPDATE task SET due_date = CURRENT_DATE + 3 WHERE id=$1`,[rows[0].id]);
await pool.query(`UPDATE task SET due_date = CURRENT_DATE - 5 WHERE id=$1`,[rows[1].id]);
console.log("임박으로 만든 것:", rows[0].id, rows[0].title, "담당", rows[0].assignee_id, "영역", rows[0].area_id);
console.log("지연으로 만든 것:", rows[1].id, rows[1].title, "담당", rows[1].assignee_id, "영역", rows[1].area_id);
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium-1194/chrome-linux/chrome",args:["--no-proxy-server","--no-sandbox"]});
const ctx=await b.newContext({viewport:{width:1440,height:950}});
await ctx.addCookies([{name:"tb_session",value:tok({id:1,actorId:1,name:"권정혁",role:"lead",email:"l@l"}),domain:"127.0.0.1",path:"/"}]);
const p=await ctx.newPage();
await p.goto(BASE+"/tasks",{waitUntil:"networkidle"});
await p.waitForTimeout(1200);
await p.locator(".frn-skip").first().click({timeout:1500}).catch(()=>{});
await p.waitForTimeout(600);
console.log("「전체 영역」 버튼:", await p.getByRole("button",{name:"전체 영역"}).count());
console.log("select 수:", await p.locator("select").count(), await p.locator("select").evaluateAll(e=>e.map(x=>x.getAttribute("aria-label"))));
// 검사기가 하는 것 그대로 — 다만 **실패를 안 삼킨다**
await p.getByRole("button",{name:"전체 영역"}).click().then(()=>console.log("전체 영역 눌렀다")).catch(e=>console.log("전체 영역 못 누름:",e.message.slice(0,60)));
const opts = await p.locator('select[aria-label="담당"] option').evaluateAll(e=>e.map(x=>`${JSON.stringify(x.value)}=${x.textContent.trim()}`));
console.log("담당 select 선택지:", opts.join(" | "));
const allVal = await p.locator('select[aria-label="담당"] option').evaluateAll(e=>{const m=e.find(x=>/전체|모두|all/i.test(x.textContent));return m?m.value:null;});
console.log("「전체」에 해당하는 값:", JSON.stringify(allVal));
if (allVal !== null) await p.selectOption('select[aria-label="담당"]', allVal).then(v=>console.log("담당 비움 →",v)).catch(e=>console.log("못 비움:",e.message.slice(0,60)));
await p.waitForTimeout(1600);
console.log("지운 뒤 행 수:", await p.locator(".tt-row, tbody tr").count());
const ddays = await p.locator(".due .tt-dday").allInnerTexts();
console.log("보이는 D 표기:", ddays.join(" | ").slice(0,200));
console.log("행 수:", await p.locator(".tt-row, tbody tr").count());
for (const r of before) await pool.query(`UPDATE task SET due_date=$2 WHERE id=$1`,[r.id,r.d]);
console.log("되돌림 완료");
await ctx.close(); await b.close(); await pool.end();
